### ISSUE TITLE
Dumping question

### ISSUE THREAD

**Issue by derchr** [ClusterM/famicom-dumper-client#7]
I think I need some help related to mappers and how to choose the right one and the right pgr and chr size. I have some multicart cardridges that I want to dump, because my old famicon clone is broken.
I had success with one cardridge but whit others no mapper seems to work.
Is there a need to program own lua scrips in order to get this working? Where can I find more general information on this topic?

**Comment by kolmogorovpavel** [comment]
Dumping cartridge is close to reverse engineering work. You should know 6502 assembler and basics of Famicom architecture. First you should dump cart as NROM (mapper 0) and disassemble code to see which registers (addresses) used for switching memory banks. Then write your own lua or CS script which switches banks and reads them. And the last thing, this dumper can't dump (technically) most of old multigames carts. Actually it can dump only coolboy.
